version: 1.0.{build}
image: Visual Studio 2019
environment:
  nodejs_version: "20"
branches:
  only:
    - main  
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
build: off
test_script:
  - npm test